### ISSUE TITLE
Leading slash in VirtualHost should be stripped

### ISSUE THREAD

**Issue by Zagrebelin** [CJWorkbench/carehare#2]
Accoring  [RabbitMQ specificatiosn](https://www.rabbitmq.com/uri-spec.html) vhost segment does not include leading slash:

> `amqp_URI       = "amqp://" amqp_authority [ "/" vhost ] [ "?" query ]`
> The vhost component of the URI does not include the leading "/" character from the path. This makes it possible to refer to any vhost, not only those that begin with a "/" character.
> 

But carehare uses an 'urlparse' python function (https://github.com/CJWorkbench/carehare/blob/main/carehare/_connection.py#L35 and https://github.com/CJWorkbench/carehare/blob/main/carehare/_connection.py#L60) which does not strip leading slash.

```
>>> urllib.parse.urlparse(carehare.connect('amqp://guest:guest@172.17.0.1/sample_vhost')._url).path
'/sample_vhost'
```

**Comment by adamhooper** [comment]
Thank you for the report!

The slash is there because I misinterpreted the default -- `/` -- as meaning, a leading slash actually belongs. I guess I was wrong? The screenshots at https://www.cloudamqp.com/blog/what-is-a-rabbitmq-vhost.html suggest RabbitMQ's default is the equivalent of `amqp://authority/%2F`.

@Zagrebelin Is this causing problems for you? This will require a major-version bump, I expect, so I'd like to gauge how important it is.

**Comment by adamhooper** [comment]
Fixed in v1. Thank you, @Zagrebelin!

For my future self and other perplexed individuals, here's my interpretation of the RabbitMQ spec -- rewritten to make me feel like I'm not stupid:

* URI path `"/myvhost"` means, `"myvhost"`
* URI path `"/"` means, `""`. But it's impossible to create a vhost named `""` on RabbitMQ. So the spec encourages you to feel stupid about writing it.
* URI path of `""` means, _a "default value"_. The spec doesn't declare any default value, but all clients tend to use `"/"`.
* Most RabbitMQ servers have a lone vhost named `"/"`. The only correct, unambiguous way for a client to select it is by URL path `"/%2F"`.
* RabbitMQ's [URI spec](https://www.rabbitmq.com/uri-spec.html) is pretty darned confident about all this -- writing up a table of examples.
* Most RabbitMQ clients -- including carehare v1 -- allow a _default value_ of `"/"`.

I read all this and was still confused -- why is the default `"/"` instead of, say, `"default"`? I couldn't find an answer. It certainly appears broken, and it [creates problems](https://github.com/rabbitmq/rabbitmq-management/issues/602) with security-minded reverse proxies.

But I did find _more_ confusion, and I'll explicitly write it here for other people:

*The server cannot advertise any default vhost*. The RabbitMQ server-side `default_vhost` is a completely different beast from the client-side _default value_. It's invisible to clients. It might have been called `vhost_to_create_on_database_init` to allay confusion.

All that to say: **vhost `"/"` is not a standard: it's a convention**. And it's darned confusing convention.

From v1 onwards, carehare rewrites URL path `""` as vhost `"/"`. That's the convention users expect and it's permitted by the spec.

From v1 onwards, if carehare sees URL path `"/"` it will warn with a `DeprecationWarning` and _still_ select vhost `"/"`. This is _against_ the spec because the spec forces vhost `""`. But the value `""` is itself invalid! I'm all about following specs, but this `""` in RabbitMQ's URI spec seems to me to deliver no value at all. Pika [violates the spec](https://github.com/pika/pika/blob/1baf475547351c4f37762c5534de9ac49affed3d/pika/connection.py#L768) in this same manner; `rabbitmq-java-client` maintainers opt instead [tell users to RTFM](https://github.com/rabbitmq/rabbitmq-java-client/issues/610#issuecomment-491241470).
